[package]
name = "llm_rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
rayon = "1.5.3"
rand = "0.9.0-alpha.1"
bytemuck = "1.15.0"

libc = "0.2.153"
